language: python
python: "2.7"
env:
  - LLVM_HOME=/usr/lib/llvm-3.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8 
      - libclang-common-3.8-dev 
      - libclang-3.8-dev 
      - llvm-3.8-dev 
      - liblldb-3.8-dev 
      - python-clang-3.8
matrix:
  include:
    - python: "2.7"
      env:
        - LLVM_HOME=/usr/lib/llvm-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - clang-3.9 
            - libclang-common-3.9-dev 
            - libclang-3.9-dev 
            - llvm-3.9-dev 
            - liblldb-3.9-dev 
            - python-clang-3.9
    - python: "3.5"
      env:
        - LLVM_HOME=/usr/lib/llvm-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8 
            - libclang-common-3.8-dev 
            - libclang-3.8-dev 
            - llvm-3.8-dev 
            - liblldb-3.8-dev 
            - python-clang-3.8
install:
  - export CC=$LLVM_HOME/bin/clang
  - export CXX=$LLVM_HOME/bin/clang++
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ln -s /usr/lib/python2.7/dist-packages/clang; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install libclang-py3; fi
  - pip install pybind11
script:
  - pip install -v .
