language: python
sudo: required
dist: trusty
python:
    - "2.7"
before_install:
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y clang-3.8 libclang-common-3.8-dev libclang-3.8-dev llvm-3.8-dev liblldb-3.8-dev python-clang-3.8
    - export LLVM_HOME=/usr/lib/llvm-3.8
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - coverage run setup.py test
    - coverage report --show-missing
