language: python
sudo: required
dist: trusty
python:
    - "2.7"
before_install:
    - cmake --version
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - coverage run setup.py test
    - coverage report --show-missing
