
////////////////////////////////////////////////////////////////////////////////
// File autogenerated by clastgen
//
//  Changes made here will be overwritten.
////////////////////////////////////////////////////////////////////////////////
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "internal.h"

#include <clang/AST/AST.h>
#include <clang/ASTMatchers/ASTMatchers.h>
#include <clang/ASTMatchers/ASTMatchFinder.h>


namespace py = pybind11;

extern void autogenerated_classes_0(pybind11::module& m);
extern void autogenerated_classes_1(pybind11::module& m);
extern void autogenerated_classes_2(pybind11::module& m);
extern void autogenerated_classes_3(pybind11::module& m);

void autogenerated_classes(pybind11::module& m)
{
    autogenerated_classes_0(m);
    autogenerated_classes_1(m);
    autogenerated_classes_2(m);
    autogenerated_classes_3(m);
}
