#ifndef PYCLAST_H
#define PYCLAST_H

#include <pybind11/pybind11.h>

void install_toolmain(pybind11::module& m);
void install_wrappers(pybind11::module& m);
void install_ast_matcher_bindings(pybind11::module& m);
void install_dyntypednode(pybind11::module& m);
void autogenerated_enums(pybind11::module& m);
void autogenerated_classes(pybind11::module& m);

#endif 
